In [1]:
import pandas as pd

df = pd.read_csv("../data/tfl-journeys-type.csv")

df.head()

,Period and Financial year,Reporting Period,Days in period,Period beginning,Period ending,Bus journeys (m),Underground journeys (m),DLR Journeys (m),Tram Journeys (m),Overground Journeys (m),Emirates Airline Journeys (m),TfL Rail Journeys (m)
0,01_10/11,1.0,31.0,01-Apr-10,01-May-10,189.1,90.5,6.3,2.3,NaN,NaN,NaN
1,02_10/11,2.0,28.0,02-May-10,29-May-10,181.6,84.5,5.8,2.2,NaN,NaN,NaN
2,03_10/11,3.0,28.0,30-May-10,26-Jun-10,175.9,84.3,5.8,2.1,NaN,NaN,NaN
3,04_10/11,4.0,28.0,27-Jun-10,24-Jul-10,183.4,86.5,6.1,2.1,NaN,NaN,NaN
4,05_10/11,5.0,28.0,25-Jul-10,21-Aug-10,160.4,82.9,5.8,2.0,NaN,NaN,NaN

In [ ]:
df.shape  
df.info()  
df.isnull().sum() 
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Period and Financial year      138 non-null    str
 1   Reporting Period               138 non-null    float64
 2   Days in period                 138 non-null    float64
 3   Period beginning               138 non-null    str
 4   Period ending                  138 non-null    str
 5   Bus journeys (m)               138 non-null    float64
 6   Underground journeys (m)       138 non-null    float64
 7   DLR Journeys (m)               138 non-null    float64
 8   Tram Journeys (m)              138 non-null    float64
 9   Overground Journeys (m)        131 non-null    float64
 10  Emirates Airline Journeys (m)  109 non-null    float64
 11  TfL Rail Journeys (m)          72 non-null     float64
dtypes: float64(9), str(3)
memory usage: 13.8 KB

,Reporting Period,Days in period,Bus journeys (m),Underground journeys (m),DLR Journeys (m),Tram Journeys (m),Overground Journeys (m),Emirates Airline Journeys (m),TfL Rail Journeys (m)
count,138.000000,138.000000,138.000000,138.000000,138.000000,138.000000,131.000000,109.000000,72.000000
mean,6.855072,28.079710,169.807971,94.701449,7.954348,2.147101,11.505344,0.111376,3.669444
std,3.732968,0.640046,29.661083,20.644679,1.825773,0.377311,3.552536,0.065241,0.943568
min,1.000000,26.000000,30.200000,5.700000,1.200000,0.400000,1.000000,0.000000,0.600000
25%,4.000000,28.000000,166.300000,90.350000,7.000000,2.100000,9.050000,0.080000,3.400000
50%,7.000000,28.000000,177.000000,98.500000,8.300000,2.200000,11.300000,0.110000,3.700000
75%,10.000000,28.000000,185.075000,106.100000,9.300000,2.400000,14.500000,0.130000,4.300000
max,13.000000,31.000000,207.500000,118.200000,10.600000,2.800000,17.800000,0.530000,5.700000

In [3]:
df[df.isnull().all(axis=1)]

,Period and Financial year,Reporting Period,Days in period,Period beginning,Period ending,Bus journeys (m),Underground journeys (m),DLR Journeys (m),Tram Journeys (m),Overground Journeys (m),Emirates Airline Journeys (m),TfL Rail Journeys (m)
138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.tail(15)

,Period and Financial year,Reporting Period,Days in period,Period beginning,Period ending,Bus journeys (m),Underground journeys (m),DLR Journeys (m),Tram Journeys (m),Overground Journeys (m),Emirates Airline Journeys (m),TfL Rail Journeys (m)
131,02_19/20,2.0,28.0,03-May-20,30-May-20,32.5,6.7,1.4,0.5,1.5,0.0,0.7
132,03_19/20,3.0,28.0,31-May-20,27-Jun-20,47.0,13.3,2.1,0.7,2.8,0.0,1.2
133,04_19/20,4.0,28.0,28-Jun-20,25-Jul-20,66.7,22.2,2.9,1.0,4.5,0.0,1.6
134,05_19/20,5.0,28.0,26-Jul-20,22-Aug-20,75.2,28.8,3.6,1.0,4.8,0.1,2.0
135,06_19/20,6.0,28.0,23-Aug-20,19-Sep-20,94.8,36.3,4.2,1.2,6.2,0.1,2.2
136,07_19/20,7.0,28.0,20-Sep-20,17-Oct-20,102.1,39.5,4.5,1.4,8.4,0.0,2.5
137,08_19/20,8.0,28.0,18-Oct-20,14-Nov-20,89.0,33.7,4.1,1.0,6.4,0.0,2.1
138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = df.dropna(how='all')

In [6]:
df.shape

(138, 12)

In [7]:
df.dtypes

Period and Financial year            str
Reporting Period                 float64
Days in period                   float64
Period beginning                     str
Period ending                        str
Bus journeys (m)                 float64
Underground journeys (m)         float64
DLR Journeys (m)                 float64
Tram Journeys (m)                float64
Overground Journeys (m)          float64
Emirates Airline Journeys (m)    float64
TfL Rail Journeys (m)            float64
dtype: object

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df['Period beginning'] = pd.to_datetime(
    df['Period beginning'],
    format='%d-%b-%y'
)

df['Period ending'] = pd.to_datetime(
    df['Period ending'],
    format='%d-%b-%y'
)

In [10]:
df[['Period beginning', 'Period ending']].dtypes

Period beginning    datetime64[us]
Period ending       datetime64[us]
dtype: object

In [11]:
df = df.rename(columns={
    'Period and Financial year': 'period_financial_year',
    'Reporting Period': 'reporting_period',
    'Days in period': 'days_in_period',
    'Period beginning': 'period_beginning',
    'Period ending': 'period_ending',
    'Bus journeys (m)': 'bus_journeys',
    'Underground journeys (m)': 'underground_journeys',
    'DLR Journeys (m)': 'dlr_journeys',
    'Tram Journeys (m)': 'tram_journeys',
    'Overground Journeys (m)': 'overground_journeys',
    'Emirates Airline Journeys (m)': 'emirates_airline_journeys',
    'TfL Rail Journeys (m)': 'tfl_rail_journeys'
})

In [12]:
df.columns

Index(['period_financial_year', 'reporting_period', 'days_in_period',
       'period_beginning', 'period_ending', 'bus_journeys',
       'underground_journeys', 'dlr_journeys', 'tram_journeys',
       'overground_journeys', 'emirates_airline_journeys',
       'tfl_rail_journeys'],
      dtype='str')